"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.prisma = void 0;
require("dotenv/config");
var adapter_better_sqlite3_1 = require("@prisma/adapter-better-sqlite3");
var extension_1 = require("@prisma/client/extension");
var connectionString = "".concat(process.env.DATABASE_URL);
var adapter = new adapter_better_sqlite3_1.PrismaBetterSqlite3({ url: connectionString });
var prisma = new extension_1.PrismaClient({ adapter: adapter });
exports.prisma = prisma;
